# Generated by Django 2.2 on 2019-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('nOfEmployees', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('company_interests', models.CharField(max_length=200)),
            ],
        ),
    ]
