# Generated by Django 2.2 on 2019-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
